### ISSUE TITLE
addons.mozilla.org images not supported

### ISSUE THREAD

**Issue by blakegearin** [Ademking/BetterViewer#30]
**Describe the bug**

This does not seem to work properly on images found on Firefox add-ons.

**To Reproduce**
1. Go to https://addons.mozilla.org/en-US/firefox/addon/betterviewer/
2. Right click on a screenshot
3. Click "Open Image in New Tab"

Examples:

- https://addons.mozilla.org/user-media/previews/thumbs/266/266318.jpg?modified=1644454058
- https://addons.mozilla.org/user-media/previews/full/266/266317.png?modified=1644454060

**Expected behavior**

Image will open and have BetterViewer controls.

**Screenshots**

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/17950836/168412464-657969d5-dce5-44be-b1e6-d1874afe83dc.png">

**Desktop (please complete the following information):**
 - OS: macOS `11.5.2`
 - Browser: Firefox `100.0`
 - Version: `1.0.4`

**Additional context**

N/A

**Comment by Ademking** [comment]
@blakegearin I think this issue is not related to BetterViewer. Firefox does not allow add-ons to access / edit Firefox websites for security reasons. That's why BetterViewer (for firefox) does not work with https://addons.mozilla.org/* urls.

I'm using Chrome and It's working with firefox website.

![image](https://user-images.githubusercontent.com/12462188/168512271-d7d71f9e-9b1e-4893-8401-ce7ac2d105db.png)

**Comment by Ademking** [comment]
I'm closing this issue because it's not possible to fix it (unless firefox allows to access their website using add-ons)
