### ISSUE TITLE
Imgur upload

### ISSUE THREAD

**Issue by FatehMammadli** [Ademking/BetterViewer#36]
I wanted to ask how much is expiration date IMGBB upload ?

**Comment by Metacor** [comment]
The code for upload expiration time is set to 10 minutes *(I've tested this, and it does delete after 10 minutes)*
>fetch(`https://api.imgbb.com/1/upload?expiration=600&key=${IMGBB_TOKEN}

When editing in Photopea it seems to upload an image with a 1 minute expiration *(I think this is meant as a temporary measure in order to upload it to that website though, so I don't think this one matters)*
>fetch(`https://api.imgbb.com/1/upload?expiration=60&key=${IMGBB_TOKEN}

**Comment by FatehMammadli** [comment]
Is it private when it's uploaded to IMGBB? Sorry for lot of questions

**Comment by Ademking** [comment]
> Is it private when it's uploaded to IMGBB? Sorry for lot of questions

![image](https://user-images.githubusercontent.com/12462188/196417156-205e36d4-d56b-4e5b-9ae0-01da46a0f197.png)
