### ISSUE TITLE
Ctrl+Q in Firefox conflicts

### ISSUE THREAD

**Issue by elig0n** [Ademking/BetterViewer#46]
Hitting Ctrl+Q shows the Firefox quit confirmation dialog instead of doing "Flip vertical".
 
 - OS: Linux
 - Browser Firefox 106.0.4
 - Version 1.0.5

**Comment by Metacor** [comment]
I don't think this can be fixed, because Firefox's quit seems to ignore "preventDefault()", similar to pressing Alt + F4. _(Linux seems to be the only OS affected by this, since Windows/Mac both use "Shift + Ctrl(Cmd) + Q" instead of "Ctrl + Q")_

Whenever Adem releases v1.0.6, you will be able to use Custom Hotkeys (#41) to change "Flip Vertical" to another key.

If you don't want to wait for that, and you don't typically use Ctrl+Q, then you can disable it in Firefox's "about:config" page, by setting the option "browser.quitShortcut.disabled" to **true**.
