### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by Davilarek** [Ademking/BetterViewer#53]
No commits since last year's November, would be cool to atleast see an archival/unmaintained message :+1:

**Comment by Bamajon1974** [comment]
Following up on this project as there has not been any updates in nearly a year. 

Will BetterViewer continue to be updated?  Will the extension be updated to incorporate manifest v3 requirements by Google? 

Thanks!

**Comment by Ademking** [comment]
Hello everyone,
I deeply apologize for the lack of updates on BetterViewer. Due to commitments in my studies and work, I've been unable to dedicate time to the project recently. However, I believe in the potential of this extension and its community.
I encourage anyone interested to contribute to the project.
Thank you for your understanding and support.
