### ISSUE TITLE
BetterViewer fork 

### ISSUE THREAD

**Issue by Bamajon1974** [Ademking/BetterViewer#56]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Bamajon1974** [comment]
Has any BetterViewer fork been uploaded into the Firefox and Chrome stores? No reply from the author if the extension will be maintained and developed further.

**Comment by Ademking** [comment]
> Has any BetterViewer fork been uploaded into the Firefox and Chrome stores? No reply from the author if the extension will be maintained and developed further.

Hello @Bamajon1974,
I'm the maker of BetterViewer. I deeply apologize for the lack of updates on BetterViewer. Due to commitments in my studies and work, I've been unable to dedicate time to the project recently. However, I believe in the potential of this extension and its community.
I encourage anyone interested to contribute to the project...
Thank you for your understanding and support.

**Comment by Bamajon1974** [comment]
@Ademking thank you for the reply and update.

**Comment by Bamajon1974** [comment]
Good evening

Thank you for the reply and update. Just one question though....does the
current version of BetterView support manifest v3 before v2 extensions are
removed from the chrome webstore next year?

Thanks, Jon

**Comment by Metacor** [comment]
Currently BetterViewer is dependent on Manifest V2 APIs, and as such, would need to be modified to work with Manifest V3.

If I can remember correctly, BetterViewer listens for the Header information when a new tab is loaded, and then activates if it matches the MIME type of Image. I believe in order to stop the original page from loading, and instead load it in the extension's environment, the permission API "webRequestBlocking" is used, which is disabled in Manifest V3 and instead is replaced with "declarativeNetRequest", which requires the use of rulesets to set permissions. 

I haven't personally tried to implement the new API so I'm not sure on the exact requirements, but the viability on updating to MV3 rests on whether or not you have to explicitly state every individual website host you intend to use with rulesets. Either way, in its current state, BetterViewer is not MV3 compliant.
