### ISSUE TITLE
[Issue] Going 'back' loads an image with the extension on webpage

### ISSUE THREAD

**Issue by charakaSamawry** [Ademking/BetterViewer#6]
If an image loads in the same tab as the web page, then pressing back, to return to the web page, keeps the extension loaded with an image from the webpage you were reading, when you clicked an image, that opened in full, in the same tab.

Ie. When i press back to return to the article i was reading (that didnt open an image in full in a new tab, for some reason. Or, use an 'on page' gallery..) then the buttons and mouse controls mean i have to refresh the page to continue scrolling and using the webpage, after going back
![Screenshot 2021-12-19 005709](https://user-images.githubusercontent.com/62015653/146659703-59c8f236-a467-4e59-b197-661c5c85a195.png)

**Comment by Saucistophe** [comment]
Just had this.
I don't reproduce it every time; for instance, if I go on a github profile (e.g. https://github.com/charakaSamawry) and click on the profile picture, then go back, it's not trigger.

It does on this wikipedia page: https://en.wikipedia.org/wiki/File:Waagashi.jpg
Click the picture, click "back", boom.
Maybe it's because the URL ends with `.jpg`?

**Comment by Ademking** [comment]
@charakaSamawry @Saucistophe 
Sorry for the late reply!
I've fixed it and it's working fine. Version 1.0.3
Thank you so much 👍
