### ISSUE TITLE
Comparison with Viewhance

### ISSUE THREAD

**Issue by Bamajon1974** [Ademking/BetterViewer#7]
How does BetterViewer compare with Viewhance? I am looking for a robust, feature rich image viewer to replace Viewhance which has been removed from the Chrome extension store for a couple of years now. 

If this issue thread isn't the right place for my question, please move/delete accordingly. 

Thanks!

**Comment by Ademking** [comment]
Thank you @Bamajon1974 for your question. 
I don't know about [Viewhance](https://github.com/Deathamns/Viewhance)
I've tried it and It's very cool extension 😮 I don't know why it's deleted from Chrome extension store...

This is my honest comparison:

|  Feature  |  BetterViewer | Viewhance |
|---|:-:|:-:|
| Zoom in / Zoom Out / Reset  | ✅ | ✅ |
| Fullscreen | ✅ | ❌ |
| Rotate Left / Rotate Right | ✅ | ✅ |
| Flip Horizontal / Flip Vertical | ✅ | ✅ |
| Crop Image | ✅  | ❌ |
| Paint | ✅ | ❌ |
| Download Image | ✅  | ❌ |
| Upload Image to imgBB | ✅ | ❌ |
| Color picker | ✅ | ❌ |
| Image Details | ✅  | ❌ |
| Change background color (Dark / Light / Blurred) | ✅  |  ✅ |
| Print Image | ✅ | ❌ |
| Extract Text from Image | ✅ | ❌ |
| Edit in Photopea (Thanks to @bbbenji) | ✅  | ❌ |
| Reverse Image Search (using TinEye) | ✅ | ✅ |
| QR Code Scanner | ✅ | ❌ |
| Settings to customize Toolbar | ✅ | ✅ |
| Default sizing modes and switching between them via shortcuts or with mouse clicks | ✅ | ✅ |
| Custom CSS (background color for the page or media, hidden scrollbars...) | ⚠️(Not CSS Modification but you can modify the background) | ✅ |
| Custom information about the media in the tab title | ❌ | ✅ |
| Floating menu (mouse cursor over the top-left) | ❌ | ✅ |
| Mouse wheel zooming (off by default) | ✅  | ✅ |
| Centering content (default) | ✅ | ✅ |
| Rotate/Flip (via shortcuts or from the menu) | ✅  | ✅ |
| Sending the address of the media to different services (such as reverse image search) | ⚠️ Not customizable but exists | ✅ |
| Frame extraction for animated images (GIF, APNG, WEBP) | ❌  | ✅ |
| Handling SVG and data:URIs | ⚠️ Working on it (Available in the next version) | ✅ |
| Forced inlining (show media instead of download) | ❌ | ✅ |
| Native DASH, HLS, MSS streaming (if the browser can support it) | ❌ | ✅ |
| Customizable media attributes (autoplay, loop, controls, mute, volume) | ❌ | ✅ |
| Opening images from regular web-pages with right long-press or with shortcut (off by default) | ❌ | ✅ |

Try BetterViewer and Viewhance! They are both great
